# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20160503_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(related_name='books', to='book.Tag'),
        ),
    ]
