# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_book_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='books', to='book.Tag'),
        ),
    ]
