# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20160503_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='url',
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.TextField(blank=True),
        ),
    ]
